name: 'SBOM Workspace Action'
description:
  'An action for facilitating interfacing with ServiceNow SBOM Workspace.'
inputs:
  # Secrets
  sn-sbom-user:
    description: 'Platform Username.'
    required: true
  sn-sbom-password:
    description: 'Platform Password.'
    required: true
  sn-instance-url:
    description: 'The URL of the ServiceNow Platform instance.'
    required: true
  gh-token:
    description: 'The GitHub Token of the SBOM provider repository.'
    required: false

  # Arguments
  gh-account-owner:
    description: 'The owner of the provider GitHub repository.'
    required: false
  provider:
    description: 'The provider type.'
    required: true
    default: 'repository'
  args:
    description: "An object that captures the action's arguments."
    required: false
  repository:
    description: 'The repository from which the SBOM will be picked.'
    required: false
  path:
    description:
      'The absolute path from repository root to the SBOM document to be picked.'
    required: false

  # POST/Upload API Arguments
  business-application-id:
    description:
      'SYS ID of the business application to map with the root application of
      given SBOM.'
    required: false
  business-application-name:
    description:
      'Name of business application to map with the root application of given
      SBOM.'
    required: false
  build-id:
    description: 'Build ID of the SBOM build.'
    required: false
  product-model-id:
    description:
      'SYS ID of product model to map with the root application of given SBOM.'
    required: false
  requested-by:
    description: 'Determines if devops workflow is executed.'
    required: false
  lifecycle-stage:
    description:
      'Life cycle stage of the entity (i.e., production, pre_production).'
    required: false
  fetch-vulnerability-info:
    description: 'Flag to run the vulnerability intelligence integration.'
    required: false
  fetch-package-info:
    description: 'Flag to run the package intelligence integration.'
    required: false
  source-sbom:
    description: 'The source of the SBOM.'
    required: false

branding:
  icon: 'refresh-ccw'
  color: 'green'
runs:
  using: 'node20'
  main: 'dist/index.js'
