name: 'SBOM Workspace Action'
description: 'An action for facilitating interfacing with ServiceNow SBOM Workspace.'
inputs:

  # Secrets
  sn-sbom-user:
    description: 'Platform Username.'
    required: true
  sn-sbom-password:
    description: 'Platform Password.'
    required: true
  sn-instance-url:
    description: 'The URL of the ServiceNow Platform instance.'
    required: true
  gh-token:
    description: 'The GitHub Token of the SBOM provider repository.'
    required: false

  # Arguments
  gh-account-owner:
    description: 'The owner of the provider GitHub repository.'
    required: false
  provider:
    description: 'The provider type.'
    required: true
    default: 'repository'
  args:
    description: "An object that captures the action's arguments."
    required: false
  repository:
    description: 'The repository from which the SBOM will be picked.'
    required: false
  path:
    description: 'The absolute path from repository root to the SBOM document to be picked.'
    required: false

  # POST/Upload API Arguments
  business-application-id:
    description: 'The business application ID associated with the targeted SBOM.'
    required: false
  business-application-name:
    description: 'The business application name associated with the targeted SBOM.'
    required: false
  build-id:
    description: 'The build ID associated with generating the targeted SBOM.'
    required: false
  product-model-id:
    description: 'The product model ID associated with the targeted SBOM.'
    required: false
  requested-by:
    description: 'ASK ABOUT WHAT DESCRIPTION FITS HERE.'
    required: false
  lifecycle-stage:
    description: 'Denotes which environment for which this SBOM was generated (i.e., production, pre_production).'
    required: false
  fetch-vulnerability-info:
    description: 'Flag to enable the vulnerability intelligence workflow.'
    required: false
  fetch-package-info:
    description: 'Flag to enable the package intelligence workflow.'
    required: false

branding:
  icon: 'refresh-ccw'
  color: 'green'
runs:
  using: 'node20'
  main: 'dist/index.js'
